"""Turn azure-settings.txt (pasted from the Azure portal) into a local .env.

azure-settings.txt holds the Function App's Environment variables > Advanced edit
JSON, and optionally a line with the Foundry resource's Key 1. Run:

    python scripts/settings_to_env.py

Settings that only work inside Azure (managed identity, storage, Key Vault and
Cosmos through the app's identity) are left out, so the local app uses keys and
local fallbacks instead of stalling on credentials it cannot get.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "azure-settings.txt"
TARGET = ROOT / ".env"

AZURE_ONLY = {
    "AzureWebJobsStorage", "FUNCTIONS_EXTENSION_VERSION", "FUNCTIONS_WORKER_RUNTIME",
    "APP_ENV", "PUBLIC_BASE_URL", "AZURE_USE_MANAGED_IDENTITY",
    "AZURE_KEYVAULT_URL", "AZURE_KEYVAULT_KEY_NAME", "AZURE_COSMOS_ENDPOINT",
    "APPLICATIONINSIGHTS_CONNECTION_STRING", "WEBSITE_RUN_FROM_PACKAGE",
    "SCM_DO_BUILD_DURING_DEPLOYMENT", "ENABLE_ORYX_BUILD",
}


def main() -> int:
    if not SOURCE.exists():
        print(f"missing {SOURCE.name}: paste the portal settings into it first")
        return 1
    raw = SOURCE.read_text(encoding="utf-8-sig")
    start, end = raw.find("["), raw.rfind("]")
    if start < 0 or end < 0:
        print("no JSON array found: copy all of Environment variables > Advanced edit")
        return 1
    settings = {item["name"]: str(item.get("value", "")) for item in json.loads(raw[start : end + 1])}

    leftover = raw[:start] + raw[end + 1 :]
    if "AZURE_FOUNDRY_API_KEY" not in settings:
        key = re.search(r"\b[A-Za-z0-9]{32,90}\b", leftover)
        if key:
            settings["AZURE_FOUNDRY_API_KEY"] = key.group(0)

    lines = ["# Generated by scripts/settings_to_env.py. Never commit this file.", "APP_ENV=local"]
    lines += [f"{name}={value}" for name, value in sorted(settings.items()) if name not in AZURE_ONLY]
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")

    names = [name for name in sorted(settings) if name not in AZURE_ONLY]
    print(f"wrote {TARGET.name} with {len(names)} settings: {', '.join(names)}")
    if "AZURE_FOUNDRY_API_KEY" not in settings:
        print("note: no Foundry key found; model features stay on local fallbacks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
